from . import suivi_client
from . import suivi_chauffeur
from . import suivi_operation
from . import suivi_produit
from . import suivi_fournisseur
from . import suivi_stock_move
from . import suivi_stock_stock
from . import suivi_stock_entry
from . import suivi_gazoil
from . import suivi_avance
from . import suivi_charge
