{
    'name': 'Kal3iya',
    'summary': 'Module pour la gestion du stock de Casa et Tanger',
    'author': 'Ayoub Akhrif',
    'category': 'Inventory',
    'version': '1.0',
    'depends': ['base', 'mail'],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'views/product_entry_views.xml',
        'views/product_sortie_views.xml',
        'views/product_stock_views.xml',
        'views/client_view.xml',
        'reports/report_client_week_invoice.xml',
        'views/client_week_invoice_wizard_view.xml',
        'views/data_views.xml',
        'views/advance_view.xml',
        'views/driver_view.xml',
        'views/popup_sortie_view.xml',
        'views/week_update_wizard_view.xml',
    ],
    'images': ['static/description/icon.svg'],
    'installable': True,
    'application': True,
    'assets': {
        'web.assets_backend': [
            'kal3iya/static/js/week_grouped_html.js',
        ],
    },
    'license': 'LGPL-3',
}
