{
    'name': 'finance',
    'summary': 'Module pour la gestion finance',
    'author': 'Ayoub Akhrif',
    'category': 'Accounting',
    'version': '1.0',
    'depends': ['base', 'mail', 'logistique', 'douane'],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'views/data_cheque_view.xml',
        'views/data_views.xml',
        'views/benif_view.xml',
        'views/talon_view.xml',
        'views/deletion_request.xml',
        'views/cheque_request.xml',
        'views/edit_request_view.xml',
        'views/cheque_encaisse_view.xml',
        'views/logistics_integration_view.xml',
        'views/finance_deduction_view.xml',
        'views/finance_sutra_view.xml',
        'reports/cheque_request_report.xml',
        'data/cron.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'finance/static/src/css/finance_ui.css',
            'finance/static/src/js/finance_loader.js',
        ],
    },
    'images': ['static/description/icon.svg'],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
